more changes

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -79,6 +79,12 @@ jobs:
         cd terraform  # Change this to the directory containing your .tf files
         terraform init
 
+    - name: Import existing resources
+      run: |
+        cd terraform  # Change this to the directory containing your .tf files
+        terraform import google_compute_network.vpc projects/${{ secrets.GCP_PROJECT_ID }}/global/networks/***-vpc
+      continue-on-error: true
+
     - name: Terraform Plan
       run: |
         cd terraform  # Change this to the directory containing your .tf files
@@ -92,13 +98,15 @@ jobs:
         terraform apply -auto-approve tfplan
       continue-on-error: true
 
-    - name: Terraform Destroy on Failure
+    - name: Check Apply Outcome
       if: steps.apply.outcome == 'failure'
+      run: |
+        echo "Terraform apply failed"
+        exit 1
+
+    - name: Terraform Destroy on Failure
+      if: failure()
       run: |
         cd terraform  # Change this to the directory containing your .tf files
         echo "Apply failed, destroying resources..."
         terraform destroy -auto-approve -var="project_id=${{ secrets.GCP_PROJECT_ID }}" -var="api_image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/api-image:${{ github.sha }}"
-
-    - name: Check Apply Outcome
-      if: steps.apply.outcome == 'failure'
-      run: exit 1
